version: '3.1'

services:

  uimdfe:
    container_name: 'uimdfe'
    hostname: uimdfe
    image: uimdfe:release
    ports:
      - "80:80"
      - "443:443"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/letsencrypt/live/3gbrasil.com.br/fullchain.pem:/etc/letsencrypt/live/3gbrasil.com.br/fullchain.pem
      - /etc/letsencrypt/live/3gbrasil.com.br/privkey.pem:/etc/letsencrypt/live/3gbrasil.com.br/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
